version: '3.8'
services:
  app:
    image: macterra/artx-market
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      ARCHIVER: http://archiver:5115
      IPFS_HOST: ipfs
      ARTX_NAME: ${ARTX_NAME}
      ARTX_HOST: ${ARTX_HOST}
      SATSPAY_HOST: ${SATSPAY_HOST}
      SATSPAY_ADMIN_KEY: ${SATSPAY_ADMIN_KEY}
      SATSPAY_API_KEY: ${SATSPAY_API_KEY}
      SATSPAY_LN_WALLET: ${SATSPAY_LN_WALLET}
    depends_on:
      - archiver

  ipfs:
    image: ipfs/go-ipfs:v0.20.0
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data:/export/data
      - ./dist/ipfs:/data/ipfs

  archiver:
    image: macterra/artx-archiver
    ports:
      - "5115:5115"
    volumes:
      - ./data:/app/data
    environment:
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
      - BTC_CONNECT=${BTC_CONNECT}
    depends_on:
      - ipfs

  pinner:
    image: macterra/artx-pinner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    depends_on:
      - ipfs
