version: '3.8'
services:
  app:
    image: macterra/artx-market
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      ARCHIVER: http://archiver:5115
      IPFS_HOST: ipfs
      ARTX_NAME: ${ARTX_NAME}
      ARTX_HOST: ${ARTX_HOST}
      LN_HOST: ${LN_HOST}
      LN_ADMIN_KEY: ${LN_ADMIN_KEY}
      LN_API_KEY: ${LN_API_KEY}
      LN_WALLET: ${LN_WALLET}
      NOSTR_KEY: ${NOSTR_KEY}
      NOSTR_RELAYS: ws://nostr:7777,ws://100.123.100.48:4848
      NOSTR_ANNOUNCE: sale,list
      NOTARIZE_FREQUENCY: 120
      NOTARIZE_MIN_FEE: 2
      NOTARIZE_MAX_FEE: 6
      NOTARIZE_RBF_RATE: 2
    depends_on:
      - archiver
      - nostr

  ipfs:
    image: ipfs/go-ipfs:v0.20.0
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data:/export/data
      - ./ipfs:/data/ipfs

  archiver:
    image: macterra/artx-archiver
    ports:
      - "5115:5115"
    volumes:
      - ./data:/app/data
    environment:
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
      - BTC_CONNECT=${BTC_CONNECT}
      - X_API_KEY=${X_API_KEY}
      - X_API_SECRET=${X_API_SECRET}
      - X_BOT_KEY=${X_BOT_KEY}
      - X_BOT_SECRET=${X_BOT_SECRET}
    depends_on:
      - ipfs

  pinner:
    image: macterra/artx-pinner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    depends_on:
      - ipfs

  nostr:
    image: dockurr/strfry:latest
    ports:
      - 7777:7777
    volumes:
      - ./nostr/strfry-db:/app/strfry-db
      - ./nostr/strfry.conf:/etc/strfry.conf
